> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 2 - Tugas 26

> 18 Juni 2024
---
---

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

import warnings
warnings.filterwarnings('ignore')

In [165]:
df = pd.read_csv('netflix.csv')
# df.head()

In [168]:
df.dropna(subset=['date_added'], inplace=True)

In [177]:
df.isna().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7777 entries, 0 to 7786
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          7777 non-null   object
 1   type             7777 non-null   object
 2   title            7777 non-null   object
 3   director         7777 non-null   object
 4   cast             7059 non-null   object
 5   country          7271 non-null   object
 6   date_added       7777 non-null   datetime64[ns]
 7   release_year     7777 non-null   int64
 8   rating           7770 non-null   object
 9   listed_in        7777 non-null   object
 10  description      7777 non-null   object
 11  duration_number  7777 non-null   int64
 12  duration_unit    7777 non-null   object
dtypes: datetime64[ns](1), int64(2), object(10)
memory usage: 850.6+ KB

:

In [162]:
df.isna().sum()

show_id            0
type               0
title              0
director        2379
cast             718
country          506
date_added         0
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

# Data Cleaning

In [170]:
df[['duration_number', 'duration_unit']] = df['duration'].str.split(' ', expand = True)

df['duration_unit'] = df['duration_unit'].str.replace('s', '')

df['duration_number'] = pd.to_numeric(df['duration_number'])

df.drop('duration', axis = 1, inplace = True)

df.director.fillna('Unknown', inplace = True)

df.date_added.dropna(inplace = True)

df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], format='%B %d, %Y')

In [175]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,duration_number,duration_unit
0,s1,TV Show,3%,Unknown,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,4,Seaon
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,2016-12-23,2016,TV-MA,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,93,min
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,2018-12-20,2011,R,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",78,min
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,2017-11-16,2009,PG-13,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",80,min
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,2020-01-01,2008,PG-13,Dramas,A brilliant group of students become card-coun...,123,min
5,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,2017-07-01,2016,TV-MA,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...,1,Seaon
6,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,2020-06-01,2019,TV-MA,"Horror Movies, International Movies","After an awful accident, a couple admitted to ...",95,min
7,s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,2019-11-01,1997,R,Dramas,After one of his high school students attacks ...,119,min
8,s9,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,2019-04-01,2019,TV-14,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w...",118,min
9,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,2017-12-15,2008,TV-MA,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...,143,min